### PR TITLE
Fixes memory leak on doFold

### PR DESCRIPTION
**Pull request by aycanirican**

### CODE REVIEW

**Comment by nurpax** [comment]
@aycanirican How can I reproduce the leak myself?  Just a large select?

I'd like to drop the unnecessary cosmetic changes from this commit.  Other source files in this project do not follow the same aligned imports and don't split language extensions into their own lines.

**Comment by aycanirican** [comment]
@nurpax Sorry you're right, this is due to my stylish-haskell-mode, I'm going to clean it up to fit project's code style, I should check the commit before opening up a pull request. Here is a simple example that demonstrates the problem:

Folding numbers to get a sum. This example takes 107MB memory to complete in my machine. I guess doFold doesn't force evaluation of each result in it's recursion. Forcing the result via `seq` before getting the next element reduces the memory usage.

```
instance FromRow Int where
  fromRow = field

main = do
  conn <- DB.open "test.db"
  -- execute_ conn "CREATE TABLE IF NOT EXISTS test (num INT)"
  -- forM_ ([1..1000000]::[Int]) (\x -> execute conn "INSERT INTO test (num) VALUES (?)" (Only x))
  r <- (fold_ conn ("SELECT num FROM test") 0 (\a b -> return $ a + b)) :: IO Int
  print r
  DB.close conn
```

**Comment by aycanirican** [comment]
@nurpax could you please take a look at latest state of this PR?

**Comment by nurpax** [comment]
I cherry-picked your latest commit and pushed to master.  

BTW, I tried running https://github.com/nurpax/db-bench with and without this change but I didn't really see any difference.  I would've expected the extra memory to cost performance too.

**Pull request closed without merging**
