### PR TITLE
allow FromField Text and friends to accept more field types

### PR DESCRIPTION
**Pull request by goertzenator**
PR as requested by @sigrlami

- Ref case #98
- This fix works well for my project.

To be clear, this is a mitigation for case #98 for an already poisoned (with non-text sql type) database.  We also need a fix to prevent poisoning to begin with which is not addressed here at all.

### CODE REVIEW

**Comment by sigrlami** [comment]
@goertzenator finally finished with tests, integrating, it will be packaged with few other updates soon. Thank you!

**Review by sigrlami — COMMENTED** [review]
LGTM!

**Comment by goertzenator** [comment]
I would like to propose reverting this PR.

As per new comments in case #98, I've found and fixed the true root cause of my problems.  This PR papered over the real cause.

There might be good arguments for a PR that can handle all type mismatches, but this PR was focused on just a single one that affected me.  Furthermore, this PR causes test failures (as per issue #108); the easiest course is to just revert this.

**Comment by jchia** [comment]
I think I'm going to revert that commit because it's too ad-hoc and as not the really solve your actual problem.

The commit specifically allows conversion from `SQLText`, `SQLInteger` and `SQLFloat` to `Text` but if this flexible conversion to `Text` is allowed, there is no good reason to not also allow flexible conversion from `SQLText` to an integral type like `Word32`. If the flexible conversion is to be allowed, it should be done holistically consistently, by addressing other conversion pairs and properly updating unit tests.

**Pull request merged**
